language: ruby
cache:
  directories:
    - vendor/bundle
sudo: false
rvm:
  - "2.2.1"
notifications:
  email: false
bundler_args: --without development:production --deployment --retry=3 --jobs=3
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: bundle exec rake test
addons:
  postgresql: "9.3"
services:
  - redis-server
